# Generated by Django 6.0.3 on 2026-04-06 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('email_institucional', models.EmailField(max_length=254, unique=True)),
                ('escola_matricula', models.CharField(max_length=255)),
                ('idade', models.PositiveIntegerField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='alunos/fotos/')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EvolucaoDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Observação', 'Observação'), ('Interação Social', 'Melhora na interação social'), ('Nova Estratégia', 'Nova estratégia de apoio'), ('Meta Alcançada', 'Meta alcançada')], max_length=50)),
                ('descricao', models.TextField()),
                ('data_registro', models.DateField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolucoes', to='api.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='PEI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.CharField(max_length=255)),
                ('metas', models.TextField()),
                ('adaptacoes', models.TextField()),
                ('estrategias_pedagogicas', models.TextField()),
                ('nivel_suporte', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')])),
                ('proxima_revisao', models.DateField()),
                ('status', models.CharField(choices=[('Em elaboração', 'Em elaboração'), ('Aprovado', 'Aprovado')], default='Em elaboração', max_length=20)),
                ('comunicacao_progresso', models.IntegerField(default=0)),
                ('humor_progresso', models.IntegerField(default=0)),
                ('interacao_progresso', models.IntegerField(default=0)),
                ('cognicao_progresso', models.IntegerField(default=0)),
                ('autonomia_progresso', models.IntegerField(default=0)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pei', to='api.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='LaudoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='laudos/')),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('pei', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laudos', to='api.pei')),
            ],
        ),
    ]
