# Generated by Django 6.0.3 on 2026-04-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='comunicacao',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='aluno',
            name='diagnostico',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='humor',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='aluno',
            name='motor',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='aluno',
            name='social',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
