# Generated by Django 6.0.3 on 2026-04-20 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_aluno_comunicacao_aluno_diagnostico_aluno_humor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocoloCrise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gatilhos_especificos', models.TextField(help_text='O que costuma desencadear a crise neste aluno?')),
                ('sinais_alerta', models.TextField(help_text='O que o aluno faz ANTES da crise? (Ex: balançar mãos, gritar)')),
                ('plano_acao', models.TextField(help_text='Passo a passo do que o educador deve fazer.')),
                ('o_que_evitar', models.TextField(blank=True, help_text='O que piora a situação?', null=True)),
                ('contato_emergencia', models.CharField(blank=True, max_length=100, null=True)),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='protocolo_crise', to='api.aluno')),
            ],
        ),
    ]
