# Generated by Django 6.0.3 on 2026-04-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_protocolocrise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evolucaodiaria',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='laudomedico',
            name='cid',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='protocolocrise',
            name='gatilhos_especificos',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='protocolocrise',
            name='o_que_evitar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='protocolocrise',
            name='plano_acao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='protocolocrise',
            name='sinais_alerta',
            field=models.TextField(),
        ),
    ]
