# Generated by Django 6.0.3 on 2026-05-01 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_evolucaodiaria_descricao_alter_laudomedico_cid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='comunicacao',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='humor',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='motor',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='social',
        ),
        migrations.AddField(
            model_name='pei',
            name='comunicacao',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='pei',
            name='humor',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='pei',
            name='motor',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='pei',
            name='professor_responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.professor'),
        ),
        migrations.AddField(
            model_name='pei',
            name='social',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='pei',
            name='metodologia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pei',
            name='objetivos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
