# Generated by Django 6.0.3 on 2026-05-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_aluno_comunicacao_remove_aluno_humor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pei',
            name='nome_plano',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
