# Generated by Django 6.0.3 on 2026-05-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_pei_nome_plano'),
    ]

    operations = [
        migrations.AddField(
            model_name='pei',
            name='protocolo_crise',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
