"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.3.
"""

from pathlib import Path
from datetime import timedelta # <-- Importante para o tempo do Token JWT

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5*0py-jzlj-f!l2!!n@yq)d^7c&&+1w4utrc&1f3*cx++rga4i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1'] # Adicionado para garantir o funcionamento local


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # --- Bibliotecas de Terceiros ---
    'rest_framework',        
    'rest_framework_simplejwt', 
    'corsheaders',          
    'drf_spectacular',
    
    # --- Seus Apps ---
    'api',       
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    
    # --- CORS MIDDLEWARE (Obrigatório estar no topo, antes do Common) ---
    'corsheaders.middleware.CorsMiddleware',
    
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'spectra_db',       
        'USER': 'postgres',           
        'PASSWORD': 'erick123', 
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'pt-br' # Alterado para português para melhorar mensagens de erro do Django
TIME_ZONE = 'America/Sao_Paulo' # Ajustado para o fuso horário brasileiro
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = 'static/'


# ==========================================
# CONFIGURAÇÕES DO REST FRAMEWORK (API)
# ==========================================
REST_FRAMEWORK = {
    # Define o Swagger (Spectacular) para a documentação
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    
    # Define o JWT como padrão de autenticação
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    
    # Define que as rotas precisam de login por padrão (você pode liberar rotas específicas depois)
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    )
}

# Configurações extras de aparência do Swagger
SPECTACULAR_SETTINGS = {
    'TITLE': 'Spectra API',
    'DESCRIPTION': 'Documentação do sistema de apoio ao PEI',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# ==========================================
# CONFIGURAÇÕES DO CORS (Next.js)
# ==========================================
# Permite que o Frontend do Next.js (porta 3000) acesse o Django
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
]

# ==========================================
# CONFIGURAÇÕES DO JWT (TOKEN DE LOGIN)
# ==========================================
SIMPLE_JWT = {
    # O token de acesso vai durar 1 dia (ideal para testes locais)
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'AUTH_HEADER_TYPES': ('Bearer',),
}